heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  master:
    type: string
  network:
    type: string
#  db_rootpassword:
#    type: string
  metadata:
    type: json


resources:
  db-slave-server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      networks:
        - network: {get_param: network}
      user_data_format: SOFTWARE_CONFIG

  db-config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: master
        - name: host
#        - name: db_rootpassword
      group: script
      config:
        get_file: db-slave.sh

  db-slave-deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: db-config
      server:
        get_resource: db-slave-server
      input_values:
        master: { get_param: master }
        host: { get_attr: [db-slave-server, first_address] }
#        db_rootpassword: { get_param: db_rootpassword }

  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [db-slave-server, first_address]}
      protocol_port: 3306
