heat_template_version: 2015-04-30
description: AutoScaling Wordpress
parameters:
  image:
    type: string
    description: Image used for servers
    default: CentOS-7-x86_64
  key:
    type: string
    description: SSH key to connect to the servers
    default: cloudkey1
  flavor:
    type: string
    description: flavor used by the web servers
    constraints:
      - allowed_values: [m1.small, m1.medium]
  database_flavor:
    type: string
    description: flavor used by the db server
    constraints:
      - allowed_values: [m1.small, m1.medium]
  private_network:
    type: string
    description: Network used by the server
    default:  71717835-9853-4157-9caf-170b5eba23c7
  private_subnet:
    type: string
    description: subnet on which the load balancer will be located
    default: private_network
  database_name:
    type: string
    description: Name of the wordpress DB
    default: wordpress
  database_user:
    type: string
    description: Name of the wordpress user
    default: wordpress
  public_network:
    type: string
    description: UUID of a Neutron external network
    default: public_network
    
resources:
  database_password:
    type: OS::Heat::RandomString
    
  mysql:
    type: https://raw.githubusercontent.com/thaiopen/privatecloud/master/mysql-env.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      database_name: {get_param: database_name}
      database_user: {get_param: database_user}
  

